# Base recomendada pela equipe do Flutter.
include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true      
    strict-inference: true  
    strict-raw-types: true  

  errors:
    always_declare_return_types: error
    unawaited_futures: error 

linter:
  rules:
    # --- Segurança / correção ---
    - avoid_print              
    - unawaited_futures        
    - always_declare_return_types

    # --- Imutabilidade / previsibilidade ---
    - prefer_final_locals      
    - prefer_final_in_for_each

    # --- uniformidade de estilo ---
    - prefer_single_quotes     
    - require_trailing_commas  
    - directives_ordering      
    - sort_pub_dependencies    
